### PR TITLE
C# mapping file separated from the app

### PR DESCRIPTION
**Pull request by warpech**
This is a simpler form of the same proposal as in https://github.com/StarcounterApps/Images/pull/116

As part of the blending discussion (https://github.com/Starcounter/RebelsLounge/issues/154 step 2), I have tried to separate the calls to `Blender.MapUri` from the app code. 

## The good 

Starcounter supports loading uncompiled single file C#.

Run it using `star Images_Map.cs`

## The bad

It requires starting the map C# file manually after starting the app actual app. 

## Big question

Would we be comfortable in applying this in all our prefab apps and documenting it, before we have Markdown maps?

cc @StarcounterApps/starcounter, @alemoi, @mmnosek, @tomalec, @Mackiovello

### CODE REVIEW

**Comment by Mackiovello** [comment]
> Would we be comfortable in applying this in all our prefab apps and documenting it, before we have Markdown maps?

I think that would be fine. It should be documented on the blog instead of in the actual docs since it's temporary.

**Comment by warpech** [comment]
> It should be documented on the blog instead of in the actual docs since it's temporary.

I think that it should be documented anyway. Even though it is temporary, it is our current recommendation. Nobody can tell if it will take weeks or months to have the Markdown mapping file. See: https://github.com/Starcounter/RebelsLounge/issues/154

**Comment by tomalec** [comment]
> Would we be comfortable in applying this in all our prefab apps and documenting it, before we have Markdown maps?

For me, it's fine to apply and recommend C# mapping files before we get Markdown. I would rather doubt whether we are comfortable with applying this before we can get some automation in starting app's mapping file together with an app.

**Comment by mmnosek** [comment]
>  I would rather doubt whether we are comfortable with applying this before we can get some automation in starting app's mapping file together with an app.

This is my biggest concern. Without this, it will be very inconvenient to use.

**Comment by alemoi** [comment]
> This is my biggest concern. Without this, it will be very inconvenient to use.

The answer is generic playlists configured per database.

**Comment by LarsTjernstrom** [comment]
Having uncompiled C# files that will loaded and built when the system runs is a big security risk and should therefore be avoided. Wasn’t it proposed that we instead had a json-file for this in a specific format, which is read when the system starts?

**Comment by LarsTjernstrom** [comment]
Remove my last comment, since it was regering to the first bulllit points in the issue and we have decided to have a blend.json file

**Pull request closed without merging**
