### PR TITLE
Use uni-popover

### PR DESCRIPTION
**Pull request by warpech**
Work in progress. Do not merge yet.

I tried to use `uni-popover` (https://github.com/Starcounter/uniform/pull/201) with SignIn. So far, I cannot get it to render, because the rendered handle has 0px width. @alshakero can you pls take a look?

2018-10-24 09_07_30-window

### CODE REVIEW

**Comment by alshakero** [comment]
I fixed the styles of unsigned in mode. Please use `Blending#master` because I pushed a quick [fix](https://github.com/Starcounter/Blending/pull/314) there too.

**Comment by warpech** [comment]
This PR is broken after a forced push to `master`. @joozek78 will rebase.

**Comment by joozek78** [comment]
@warpech Rebased. Commit structure is different, but the resulting code should be equivalent. Please let me know if something is wrong. Old version of the code is available on tag [old-use-uni-popover](https://github.com/Starcounter/SignIn/tree/old-use-uni-popover). This tag should be removed when this PR is closed, or earlier

**Comment by warpech** [comment]
I will make this branch workable during the weekend.

**Comment by warpech** [comment]
Below gif shows how it looks now. I think that this PR should be merged and cosmetic fixes should go in another PRs:

bug

**Comment by warpech** [comment]
@joozek78 if you agree, I will merge.

**Pull request merged**
